import Head from "next/head";
import Image from "next/image";
import AboutMeCover from "../components/index_page/about_me_cover";
import IndexPageHeader from "../components/index_page/index_page_header";
import MyProjectsCover from "../components/index_page/my_projects_cover";

export default function Home() {
  return (
    <div style={{ margin: 0 }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <IndexPageHeader />
      <MyProjectsCover />
      <AboutMeCover/>
    </div>
  );
}
