import Head from "next/head";
import MyProjectsHeader from "../components/my-projects/my_projects_header";
import Projects from "../components/my-projects/projects";
import Specialties from "../components/my-projects/specialties";

import NavBar from "../components/nav_bar";

export default function MyProjects() {
  return (
    <div style={{ margin: 0 }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <MyProjectsHeader />
      <Projects />
      <Specialties />
    </div>
  );
}
